---
title: "BCA_Mp2p6n"
author: "Shruti"
date: "30/01/2023"
output: html_document
---

```{r}
library(spatstat)
#------------------------------------------------------------------#

# Read file names from the path into a vector
files <- list.files(path = "~/Downloads/BCA_RDS_new_total/", full.names = TRUE)

```

```{r}
df <- data.frame(matrix(ncol = 568, nrow = 0))

for (file_index in 1:length(files)) {
  
  # Read each file and parse the data
  file.name <- files[file_index]
  
  # extract the name of the file 
  name.of.the.file <- basename(file.name)
  
  # print("--------------------------------------------------------------------")
  # print(file.name)
  # print("--------------------------------------------------------------------")

  MyObjectsData <- readRDS(file.name)
  
  # Identify the x and y coordinates
  x <- MyObjectsData$x
  y <- MyObjectsData$y
  marks <- MyObjectsData$marks
  MyObjectsData$marks <- as.factor(MyObjectsData$marks)
  
  # Create a point process object and display it
 # p <- ppp(x,y,c(1,max(x)),c(1,max(y)))
  
  p <- subset(MyObjectsData, marks == "Mp2p6n", drop = T)
  p$marks <- as.factor(p$marks)
  
  if(is.empty(p)) {
    
    warning("this file is empty")
    
    return(NULL)}
  print(name.of.the.file)
  
  #--------------------------------------------------------------------#
  # We now fit Strauss process with 5 microns 
  #--------------------------------------------------------------------#
  
  # # Plot the L-function for each file
  # plot(Lest(p), abs(iso - r) ~ r, main = name.of.the.file)
  
  # Computing and ploting the L-function of the dataset and choosing
  # the value r which maximises the discrepancy

  discrep <- function(r) {
    return(abs(as.function(Lest(p))(r) - r))
  }
  res <- optimise(discrep, interval = c(0, 10), maximum = TRUE)

  # # Fit the Strauss process for the maximum L-function value 
  # strauss.parameter <- res$maximum
  # 
  # X <- ppm(p ~ polynom(x,y,2), Strauss(strauss.parameter))
  
  # Instead of the above fitting, we do a profilepl fit that computes 
  # pseudologlikelihood measures in the data frame defined by rvals
  
  rvals <- seq(1, 20, by = 0.3)
  D <- expand.grid(r = rvals, sat= seq(1, 3, by=1))
  # Fit the model for several data points
  fitp <- profilepl(D, Strauss, p ~ polynom(x,y,2), aic=FALSE)
  # Plot the AIC values (for checking correctness)
  #plot(fitp)
  
  # Extract the best model
  X <- as.ppm(fitp)
  
  # Compute the interaction parameter gamma 
  gamma <- exp(X$coef[7])
  
  # Get the interaction distance
  interaction.distance <- fitp$fit$interaction$par[1]

  saturation.parameter <- fitp$fit$interaction$r
  
  # We form the data frame and populate the computed coeffients 
  fit.coeff <- c(name.of.the.file, as.numeric(X$coef[1:7]), as.numeric(gamma), as.numeric(res), as.numeric(interaction.distance$r),
                 as.numeric(saturation.parameter))
  df <- rbind(df, as.data.frame(t(fit.coeff)))

}

# Assign columns to the data frame 
names(df) <-  c("Name","Intercept","x","y","I(x^2)","I(x * y)","I(y^2)","log(Interaction)","gamma","OptL","LObj","Interaction Distance",
                "Saturation Parameter")
df

# Write CSV in Desktop
write.csv(df, file = "~/index copy/_book/PhD_code/Spatial project/Data/BCA/BCA_Mp2p6n_Geyer.csv")


```

```{r}

```

